
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'd:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface SitePreferences {
			/**
			* Lunu Enabled

				Enables/disables the Lunu integration.
			* @group LUNU_PAYMENT - Lunu Payment
			* @source [attribute](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#5) | [group](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#42)
			*/
			LunuEnabled: boolean | null;

			/**
			* Lunu App ID

				Lunu App ID
			* @group LUNU_PAYMENT - Lunu Payment
			* @source [attribute](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#13) | [group](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#43)
			*/
			LunuAppID: string | null;

			/**
			* Lunu Secret Key

				Lunu Secret Key
			* @group LUNU_PAYMENT - Lunu Payment
			* @source [attribute](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#21) | [group](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#44)
			*/
			LunuSecretKey: string | null;

			/**
			* Lunu Widget URL

				Lunu Widget URL
			* @group LUNU_PAYMENT - Lunu Payment
			* @source [attribute](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#29) | [group](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#45)
			*/
			LunuWidgetURL: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Lunu Enabled

				Enables/disables the Lunu integration.
			* @group LUNU_PAYMENT - Lunu Payment
			* @source [attribute](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#5) | [group](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#42)
			*/
			(name: 'LunuEnabled'): boolean | null;
			
			/**
			* Lunu App ID

				Lunu App ID
			* @group LUNU_PAYMENT - Lunu Payment
			* @source [attribute](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#13) | [group](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#43)
			*/
			(name: 'LunuAppID'): string | null;
			
			/**
			* Lunu Secret Key

				Lunu Secret Key
			* @group LUNU_PAYMENT - Lunu Payment
			* @source [attribute](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#21) | [group](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#44)
			*/
			(name: 'LunuSecretKey'): string | null;
			
			/**
			* Lunu Widget URL

				Lunu Widget URL
			* @group LUNU_PAYMENT - Lunu Payment
			* @source [attribute](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#29) | [group](file:d:\LINK_lunupayment\metadata\meta\system-objecttype-extensions.xml#45)
			*/
			(name: 'LunuWidgetURL'): string | null;
			
	}
}